### PR TITLE
Groups added, password erased.

### PR DESCRIPTION
**Pull request by makaleks**
WARNING: This pull request requires database recreation. User creation process was changed (see new README).

### CODE REVIEW

**Comment by pda11111** [comment]
I think, group validation need changing
At first, because not all users may have group number
At second, regular expressions a faster and stronger than ifs
We can use "[1-9]1\d", but it don't solve first problem

**Comment by makaleks** [comment]
Group is a number, so regular expression is unuserful. As was discussed, all users will have a group number (can be simply changed in future).

**Comment by makaleks** [comment]
Password erased (restored via search '#passwordAuth'), README updated, bugfix for UserAdmin.
This pull request requires requires database recreation (also, see updated README).

**Comment by makaleks** [comment]
approved by pda11111

**Pull request merged**
